# write your docker-compose code here.Use the `docker compose` command instead of the legacy `docker-compose`, as it is integrated into Docker CLI (v20.10+),eliminating the need for a separate binary. It provides better performance, consistency, and is actively maintained, unlike the legacy command.
version: '3.8'
services:
  todo-application:
    image: todo-application-image:latest
    ports: 
      - "8082:8081"
    networks:
      - to-do-network
    depends_on:
      - mysql-db
  
  mysql-db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: Root@123
      MYSQL_DATABASE: tododb
      MYSQL_USER: root
      MYSQL_PASSWORD: Nuvelabs123$
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - to-do-network

networks:
  to-do-network:

volumes:
  mysql-data: